import { APP_STORAGE_KEY } from './storage.js';
(() => {
  const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
  const KEY = APP_STORAGE_KEY;
  const todayKey = () => new Date().toISOString().slice(0, 10);
  const defaults = {settings:{theme:'blue',dark:true,amoled:false,sound:false,vibrate:true,reminder:''},dailyGoal:1000,notes:{},achievements:[],currentId:'subhanallah',lifetime:0,history:{},tasbihs:[
    {id:'subhanallah',name:'SubhanAllah',arabic:'سُبْحَانَ ٱللَّٰهِ',count:0,goal:33,favorite:true},
    {id:'alhamdulillah',name:'Alhamdulillah',arabic:'ٱلْـحَـمْـدُ للهِ',count:0,goal:33},
    {id:'allahuakbar',name:'Allahu Akbar',arabic:'ٱللَّٰهُ أَكْبَرُ',count:0,goal:34},
    {id:'istighfar',name:'Astaghfirullah',arabic:'أَسْتَغْفِرُ ٱللَّٰهَ',count:0,goal:100}
  ]};
  const library=[
    ['SubhanAllah','سُبْحَانَ ٱللَّٰهِ','Glory be to Allah','33','Remembering Allah brings peace.'],['Alhamdulillah','ٱلْـحَـمْـدُ للهِ','All praise is due to Allah','33','A reminder of gratitude.'],['Allahu Akbar','ٱللَّٰهُ أَكْبَرُ','Allah is the Greatest','34','Affirms Allah’s greatness.'],['La ilaha illallah','لَا إِلَٰهَ إِلَّا ٱللَّٰهُ','There is no god but Allah','100','The testimony of faith.'],['Astaghfirullah','أَسْتَغْفِرُ ٱللَّٰهَ','I seek Allah’s forgiveness','100','A dhikr of forgiveness.'],['SubhanAllahi wa bihamdihi','سُبْحَانَ ٱللَّٰهِ وَبِحَمْدِهِ','Glory and praise to Allah','100','A beloved daily remembrance.'],['La hawla wa la quwwata illa billah','لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِٱللَّٰهِ','There is no power except through Allah','100','A treasure from Paradise.'],['Allahumma salli ala Muhammad','اللَّهُمَّ صَلِّ عَلَىٰ مُحَمَّدٍ','O Allah, send blessings upon Muhammad','100','Send blessings upon the Prophet ﷺ.']
  ];
  // Extra built-ins keep the library useful out of the box (each can be saved as an independent counter).
  library.push(...[
    ['SubhanAllahil Azeem','سُبْحَانَ اللَّهِ الْعَظِيمِ','Glory be to Allah, the Magnificent',33],['Hasbunallahu wa ni’mal wakeel','حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ','Allah is sufficient for us',100],['Ya Rahman','يَا رَحْمَٰنُ','O Most Merciful',100],['Ya Raheem','يَا رَحِيمُ','O Most Compassionate',100],['Ya Kareem','يَا كَرِيمُ','O Most Generous',100],['Ya Latif','يَا لَطِيفُ','O Most Gentle',100],['Ya Ghaffar','يَا غَفَّارُ','O Ever-Forgiving',100],['Ya Malik','يَا مَلِكُ','O Sovereign',100],['Ya Salaam','يَا سَلَامُ','O Source of Peace',100],['Ya Noor','يَا نُورُ','O Light',100],['Ya Hadi','يَا هَادِي','O Guide',100],['Ya Wadud','يَا وَدُودُ','O Most Loving',100],['Ya Razzaq','يَا رَزَّاقُ','O Provider',100],['Rabbighfirli','رَبِّ اغْفِرْ لِي','My Lord, forgive me',100],['Rabbana Atina','رَبَّنَا آتِنَا','Our Lord, give us good',40],['Inna lillahi','إِنَّا لِلَّهِ','To Allah we belong',100],['Bismillah','بِسْمِ اللَّهِ','In the name of Allah',100],['Alhamdulillah Rabbil Aalameen','الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ','Praise to the Lord of all worlds',100],['Allahumma inni as’aluka al-afiyah','اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَافِيَةَ','O Allah, grant me well-being',100],['Rabbi zidni ilma','رَبِّ زِدْنِي عِلْمًا','My Lord, increase me in knowledge',100],['La ilaha illa anta','لَا إِلَٰهَ إِلَّا أَنْتَ','There is no god except You',100],['Allahumma a’inni ala dhikrika','اللَّهُمَّ أَعِنِّي عَلَى ذِكْرِكَ','Help me remember You',100],['A’udhu billahi minash shaytan','أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ','I seek refuge in Allah',100],['La ilaha illallah wahdahu','لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ','None is worthy of worship but Allah alone',100],['Allahumma barik ala Muhammad','اللَّهُمَّ بَارِكْ عَلَى مُحَمَّدٍ','Bless Muhammad',100],['Subhanal Malikil Quddus','سُبْحَانَ الْمَلِكِ الْقُدُّوسِ','Glory to the Holy King',33],['Ya Hayyu Ya Qayyum','يَا حَيُّ يَا قَيُّومُ','O Ever-Living, Sustainer',100],['Allah Akbar Kabira','اللَّهُ أَكْبَرُ كَبِيرًا','Allah is greatly the Greatest',100],['Ya Muqallibal Quloob','يَا مُقَلِّبَ الْقُلُوبِ','O Turner of hearts',100],['Rabbi inni lima anzalta','رَبِّ إِنِّي لِمَا أَنْزَلْتَ','My Lord, I am in need of Your good',100],['Allahumma innaka Afuwwun','اللَّهُمَّ إِنَّكَ عَفُوٌّ','O Allah, You are Pardoning',100],['Ya Dhal Jalali wal Ikram','يَا ذَا الْجَلَالِ وَالْإِكْرَامِ','O Possessor of Majesty and Honour',100],['La ilaha illallah al-Malik','لَا إِلَٰهَ إِلَّا اللَّهُ الْمَلِكُ','None is worthy except Allah, the King',100],['Ya Shafi','يَا شَافِي','O Healer',100],['Ya Tawwab','يَا تَوَّابُ','O Accepter of repentance',100],['Ya Hafeez','يَا حَفِيظُ','O Protector',100],['Ya Fattah','يَا فَتَّاحُ','O Opener',100]
  ].map(([name,arabic,meaning,goal])=>[name,arabic,meaning,String(goal),'A beneficial remembrance for daily practice.']));
  let state, session = 0, lastTouchX = null, wakeLock = null;
  const read = () => { try { return JSON.parse(localStorage.getItem(KEY)) || structuredClone(defaults) } catch { return structuredClone(defaults) } };
  // LocalStorage keeps the active state instantly available; IndexedDB maintains
  // a separate, durable per-day history record for larger future histories.
  function storeHistory(){
    if(!('indexedDB' in window)) return;
    const request=indexedDB.open('TasbihProHistory',1);
    request.onupgradeneeded=()=>request.result.createObjectStore('days',{keyPath:'date'});
    request.onsuccess=()=>{const db=request.result, tx=db.transaction('days','readwrite'), store=tx.objectStore('days');Object.entries(state.history).forEach(([date,value])=>store.put({date,...value}));tx.oncomplete=()=>db.close()};
  }
  const save = () => { localStorage.setItem(KEY, JSON.stringify(state)); storeHistory() };
  const current = () => state.tasbihs.find(t => t.id === state.currentId) || state.tasbihs[0];
  const daily = () => Object.values(state.history[todayKey()]?.items || {}).reduce((a,b)=>a+b,0);
  const fmt = n => Number(n || 0).toLocaleString();
  function applySettings(){ const s=state.settings; document.body.className=`${s.dark?'dark':''} ${s.amoled?'amoled':''} ${s.theme==='teal'?'teal-theme':s.theme==='green'?'green-theme':s.theme==='black'?'black-theme':''}`; $('#darkMode').checked=s.dark;$('#amoledMode').checked=s.amoled;$('#soundSetting').checked=s.sound;$('#vibrateSetting').checked=s.vibrate; $$('#themeChoices button').forEach(b=>b.classList.toggle('active',b.dataset.theme===s.theme)); }
  function renderHome(){ const t=current(), g=Number(t.goal)||0, p=g?Math.min(100,t.count/g*100):0, dGoal=Number(state.dailyGoal)||1000, d=Math.min(100,daily()/dGoal*100); $('#currentName').textContent=t.name;$('#arabic').textContent=t.arabic||'';$('#count').textContent=String(t.count).padStart(6,'0');$('#todayCount').textContent=fmt(daily());$('#sessionCount').textContent=fmt(session);$('#lifetimeCount').textContent=fmt(state.lifetime);$('#goalText').textContent=g?`${fmt(t.count)} of ${fmt(g)}`:'No goal set';$('#progressRing').style.setProperty('--p',p);$('#dailyGoalLabel').textContent=`${fmt(daily())} / ${fmt(dGoal)}`;$('#dailyGoalBar').style.width=d+'%'; }
  function renderLibrary(filter=''){const f=filter.toLowerCase();$('#libraryList').innerHTML=library.filter(x=>x.join(' ').toLowerCase().includes(f)).map((x,i)=>`<article class="library-item"><header><b>${x[0]}</b><button class="star" data-fav="${i}">♡</button></header><div class="lib-arabic">${x[1]}</div><p>${x[2]}</p><p>${x[4]}</p><footer><span>Target ${x[3]}</span><button data-use="${i}">Use this dhikr</button></footer></article>`).join('')||'<div class="history-empty">No dhikr found.</div>'}
  function renderTasbihs(){ const t=current(); $('#tasbihList').innerHTML=state.tasbihs.map(x=>`<div class="tasbih-item" data-id="${x.id}"><div class="circle">☾</div><div class="name">${escape(x.name)}<div class="sub">${x.goal?`Goal ${fmt(x.goal)}`:'No goal'}</div></div><div class="num">${fmt(x.count)}</div><button class="star" aria-label="Favourite">${x.favorite?'★':'☆'}</button><button class="choose">${x.id===t.id?'✓':'›'}</button></div>`).join(''); const presets=[['Morning Adhkar','SubhanAllah ×33'],['After Salah','33 · 33 · 34'],['Darood','Allahumma Salli Ala Muhammad'],['Kalima','La ilaha illallah'],['Tahleel','La ilaha illallah wahdahu…'],['Tasbih Fatima','33 · 33 · 34']];$('#presetList').innerHTML=presets.map(p=>`<button class="preset" data-name="${p[0]}"><b>${p[0]}</b><span>${p[1]}</span></button>`).join(''); }
  function escape(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function renderHistory(){const entries=Object.entries(state.history).sort((a,b)=>b[0].localeCompare(a[0]));$('#historyList').innerHTML=entries.length?entries.map(([date,v])=>{const total=Object.values(v.items).reduce((a,b)=>a+b,0);return `<article class="history-card"><div class="date-total"><h3>${new Date(date+'T00:00:00').toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'})}</h3><b>${fmt(total)}</b></div>${Object.entries(v.items).map(([id,n])=>`<div class="history-row"><span>${escape(state.tasbihs.find(t=>t.id===id)?.name||'Tasbih')}</span><b>${fmt(n)}</b></div>`).join('')}</article>`}).join(''):'<div class="history-empty">Your daily remembrance will appear here.<br>Start with one gentle tap.</div>'}
  function renderStats(){ const days=Object.entries(state.history).sort((a,b)=>a[0].localeCompare(b[0])); const totals=days.map(([d,v])=>[d,Object.values(v.items).reduce((a,b)=>a+b,0)]);const values=totals.map(x=>x[1]), high=Math.max(0,...values),avg=values.length?Math.round(values.reduce((a,b)=>a+b,0)/values.length):0;let streak=0;for(let d=new Date();;d.setDate(d.getDate()-1)){let k=d.toISOString().slice(0,10);if(state.history[k]&&Object.values(state.history[k].items).reduce((a,b)=>a+b,0)>0)streak++;else break}const favorite=state.tasbihs.find(t=>t.favorite)?.name||'None';$('#statGrid').innerHTML=[['Total zikr',fmt(state.lifetime)],['Longest streak',`${streak} days`],['Highest day',fmt(high)],['Daily average',fmt(avg)],['Favourite',favorite]].map(([a,b])=>`<article><span>${a}</span><strong>${b}</strong></article>`).join(''); const recent=totals.slice(-7), max=Math.max(1,...recent.map(x=>x[1]));$('#barChart').innerHTML=recent.length?recent.map(([d,n])=>`<div class="bar"><i style="height:${Math.max(3,n/max*100)}%"></i><span>${new Date(d+'T00:00:00').toLocaleDateString(undefined,{weekday:'narrow'})}</span></div>`).join(''):'<p class="history-empty">Seven days of progress will bloom here.</p>'; }
  function render(){state.settings ||= structuredClone(defaults.settings);state.dailyGoal ||= 1000;state.notes ||= {};state.achievements ||= [];applySettings();renderHome();renderTasbihs();renderHistory();renderStats();renderLibrary($('#librarySearch')?.value||'')}
  function tap(ev){const t=current();t.count++;state.lifetime++;session++;const day=todayKey();state.history[day] ||= {items:{}};state.history[day].items[t.id]=(state.history[day].items[t.id]||0)+1;if(state.lifetime>=100&&!state.achievements.includes('First 100'))state.achievements.push('First 100');if(state.lifetime>=1000&&!state.achievements.includes('First 1000'))state.achievements.push('First 1000');if(state.lifetime>=10000&&!state.achievements.includes('10,000 Dhikr'))state.achievements.push('10,000 Dhikr');save();renderHome();const n=$('#count');n.classList.remove('bump');void n.offsetWidth;n.classList.add('bump');const b=$('#countButton'),r=b.getBoundingClientRect(),x=(ev?.clientX||r.left+r.width/2)-r.left,y=(ev?.clientY||r.top+r.height/2)-r.top;b.style.setProperty('--x',x+'px');b.style.setProperty('--y',y+'px');b.classList.remove('ripple');void b.offsetWidth;b.classList.add('ripple');if(state.settings.vibrate&&navigator.vibrate)navigator.vibrate(12);if(state.settings.sound)beep();if(t.goal&&t.count===t.goal) setTimeout(()=>message('Alhamdulillah!','Target completed. May this remembrance bring peace to your heart.'),150)}
  function beep(){try{const c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=530;g.gain.setValueAtTime(.04,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.07);o.start();o.stop(c.currentTime+.07)}catch{}}
  function modal(html){$('#modalContent').innerHTML=html;$('#modal').showModal()}; function message(title,body){modal(`<div class="modal-body"><h2>${title}</h2><p>${body}</p><div class="modal-actions"><button value="cancel" class="primary">Wonderful</button></div></div>`)}
  function choose(id){state.currentId=id;save();show('home')}
  function show(v){$$('.view').forEach(x=>x.classList.toggle('active',x.id===v));$$('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('#drawer').classList.remove('open');$('#backdrop').classList.remove('show');render();window.scrollTo(0,0)}
  function makeCustom(name,goal=0,arabic='',translation='',notes=''){const id='custom-'+Date.now();state.tasbihs.push({id,name,arabic,count:0,goal:Number(goal)||0,translation,notes});state.currentId=id;save();show('home')}
  state=read();
  render();
  $('#countButton').addEventListener('click',tap);$('#menuBtn').onclick=()=>{$('#drawer').classList.add('open');$('#backdrop').classList.add('show')};$('#closeDrawer').onclick=$('#backdrop').onclick=()=>{$('#drawer').classList.remove('open');$('#backdrop').classList.remove('show')};$$('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));
  $('#resetCurrent').onclick=()=>modal(`<div class="modal-body"><h2>Reset ${escape(current().name)}?</h2><p>This resets only this tasbih counter.</p><div class="modal-actions"><button value="cancel" class="secondary">Cancel</button><button id="confirmReset" value="default" class="primary">Reset</button></div></div>`);$('#modal').addEventListener('click',e=>{if(e.target.id==='confirmReset'){current().count=0;save();render()}});
  $('#goalBtn').onclick=()=>modal(`<div class="modal-body"><h2>Set a goal</h2><label>Goal for ${escape(current().name)}</label><input id="goalInput" type="number" min="1" value="${current().goal||''}" placeholder="e.g. 100"><div class="modal-actions"><button value="cancel" class="secondary">Cancel</button><button id="saveGoal" value="default" class="primary">Save goal</button></div></div>`);$('#modal').addEventListener('click',e=>{if(e.target.id==='saveGoal'){current().goal=Number($('#goalInput').value)||0;save();render()}});
  $('#tasbihPicker').onclick=()=>show('tasbihs');$('#tasbihList').onclick=e=>{const row=e.target.closest('.tasbih-item');if(!row)return;let item=state.tasbihs.find(x=>x.id===row.dataset.id);if(e.target.closest('.star')){item.favorite=!item.favorite;save();renderTasbihs()}else choose(item.id)};$('#presetList').onclick=e=>{const b=e.target.closest('.preset');if(b)makeCustom(b.dataset.name,100)};
  $('#addTasbih').onclick=()=>modal('<div class="modal-body"><h2>New Tasbih</h2><label>Name</label><input id="newName" maxlength="40" placeholder="Morning Dhikr" required><label>Arabic (optional)</label><input id="newArabic" placeholder="Arabic text"><label>Translation (optional)</label><input id="newTranslation" placeholder="Meaning"><label>Target count</label><input id="newGoal" type="number" min="1" placeholder="e.g. 100"><label>Notes (optional)</label><textarea id="newNotes" rows="2" placeholder="Personal note"></textarea><div class="modal-actions"><button value="cancel" class="secondary">Cancel</button><button id="saveCustom" value="default" class="primary">Save</button></div></div>');$('#modal').addEventListener('click',e=>{if(e.target.id==='saveCustom'){let n=$('#newName').value.trim();if(n)makeCustom(n,$('#newGoal').value,$('#newArabic').value,$('#newTranslation').value,$('#newNotes').value)}});
  $('#librarySearch').oninput=e=>renderLibrary(e.target.value);$('#libraryList').onclick=e=>{const use=e.target.closest('[data-use]');if(!use)return;const l=library[use.dataset.use];let existing=state.tasbihs.find(t=>t.name===l[0]);if(!existing){existing={id:'library-'+Date.now(),name:l[0],arabic:l[1],count:0,goal:Number(l[3]),translation:l[2],benefit:l[4]};state.tasbihs.push(existing)}state.currentId=existing.id;save();show('home')};
  $('#dailyGoalBtn').onclick=$('#dailyGoalLabel').onclick=()=>modal(`<div class="modal-body"><h2>Daily goal</h2><label>Today’s target</label><input id="dailyGoalInput" type="number" min="1" value="${state.dailyGoal}"><div class="modal-actions"><button value="cancel" class="secondary">Cancel</button><button id="saveDailyGoal" value="default" class="primary">Save</button></div></div>`);$('#modal').addEventListener('click',e=>{if(e.target.id==='saveDailyGoal'){state.dailyGoal=Number($('#dailyGoalInput').value)||1000;save();renderHome()}});
  $('#noteBtn').onclick=()=>modal(`<div class="modal-body"><h2>Today’s note</h2><label>A private reflection</label><textarea id="noteInput" rows="4" placeholder="Today completed after Fajr…">${escape(state.notes[todayKey()]||'')}</textarea><div class="modal-actions"><button value="cancel" class="secondary">Cancel</button><button id="saveNote" value="default" class="primary">Save note</button></div></div>`);$('#modal').addEventListener('click',e=>{if(e.target.id==='saveNote'){state.notes[todayKey()]=$('#noteInput').value.trim();save();$('#modal').close();message('Note saved','Your reflection stays privately on this device.')}});
  $('#fingerModeBtn').onclick=async()=>{const overlay=document.createElement('div');overlay.className='finger-overlay';overlay.innerHTML=`<button aria-label="Exit finger mode">×</button><div class="finger-count">${String(current().count).padStart(6,'0')}</div><div class="finger-name">${escape(current().name)}</div><p>Tap anywhere to count</p>`;document.body.append(overlay);try{wakeLock=await navigator.wakeLock?.request('screen')}catch{}overlay.addEventListener('click',e=>{if(e.target.closest('button')){wakeLock?.release();overlay.remove();return}tap(e);overlay.querySelector('.finger-count').textContent=String(current().count).padStart(6,'0')})};
  $('#reminderBtn').onclick=async()=>{if('Notification' in window&&Notification.permission==='default')await Notification.requestPermission();modal(`<div class="modal-body"><h2>Daily reminder</h2><label>Time (opens while the app is running)</label><input id="reminderInput" type="time" value="${state.settings.reminder||''}"><div class="modal-actions"><button value="cancel" class="secondary">Cancel</button><button id="saveReminder" value="default" class="primary">Save</button></div></div>`)};$('#modal').addEventListener('click',e=>{if(e.target.id==='saveReminder'){state.settings.reminder=$('#reminderInput').value;save();message('Reminder saved','Keep Tasbih Pro open at the selected time to receive a gentle reminder.')}});setInterval(()=>{if(state?.settings?.reminder&&new Date().toTimeString().slice(0,5)===state.settings.reminder&&Notification.permission==='granted')new Notification('Tasbih Pro',{body:'Remember Allah today.'})},60000);
  $('#darkMode').onchange=e=>{state.settings.dark=e.target.checked;save();applySettings()};$('#amoledMode').onchange=e=>{state.settings.amoled=e.target.checked;save();applySettings()};$('#soundSetting').onchange=e=>{state.settings.sound=e.target.checked;save()};$('#vibrateSetting').onchange=e=>{state.settings.vibrate=e.target.checked;save()};$('#soundBtn').onclick=()=>{$('#soundSetting').click()};$('#themeChoices').onclick=e=>{let b=e.target.closest('button');if(b){state.settings.theme=b.dataset.theme;save();applySettings()}};
  $('#exportBtn').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download=`tasbih-pro-backup-${todayKey()}.json`;a.click();URL.revokeObjectURL(a.href)};$('#importInput').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(!x.tasbihs)throw 0;state=x;save();render();message('Backup restored','Your Tasbih Pro data is safely restored.')}catch{message('Could not restore','Please choose a valid Tasbih Pro backup file.')}};r.readAsText(f)};$('#resetAll').onclick=()=>modal('<div class="modal-body"><h2>Reset everything?</h2><p>This permanently removes all tasbihs, history, and settings from this device.</p><div class="modal-actions"><button value="cancel" class="secondary">Cancel</button><button id="confirmAll" value="default" class="primary">Reset all</button></div></div>');$('#modal').addEventListener('click',e=>{if(e.target.id==='confirmAll'){state=structuredClone(defaults);save();render();$('#modal').close()}});
  $('#countButton').addEventListener('touchstart',e=>lastTouchX=e.touches[0].clientX,{passive:true});$('#countButton').addEventListener('touchend',e=>{if(lastTouchX===null)return;let d=e.changedTouches[0].clientX-lastTouchX;if(Math.abs(d)>50){let i=state.tasbihs.findIndex(t=>t.id===state.currentId);i=(i+(d<0?1:-1)+state.tasbihs.length)%state.tasbihs.length;choose(state.tasbihs[i].id)}lastTouchX=null},{passive:true});
  if('serviceWorker' in navigator)navigator.serviceWorker.register('service-worker.js');
})();
